<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <FluentIconSizes>10,12,16,20,24,28,32,48</FluentIconSizes>
        <FluentIconVariants>Filled,Regular,Light</FluentIconVariants>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.3"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.3" PrivateAssets="all"/>
        <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" Version="4.11.4" />
        <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Emoji" Version="4.11.4" />
        <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" Version="4.11.4" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="wwwroot\sample-data\weather.json" />
    </ItemGroup>

    <ItemGroup>
      <Content Update="wwwroot\resources\dylan-riden-cv-02-2025.pdf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="..\..\..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>
    
</Project>
